### ISSUE TITLE
Missing arguments in WebSocketServer.handleUpgrade

### ISSUE THREAD

**Issue by Kamil93** [ClusterWS/cWS#11]
In context of compatibility with ws module, there are problem as in title of issue. Two arguments are missing: upgradeHead & callback

**Comment by smoholkar** [comment]
@goriunov using this library as it works with uws. 

```
const wss = new WebSocketServer({
  server: httpApp.server,
  verifyClient: test.verify.bind(test) // authenticates the user and sets the correct request headers
});
```
`wss.on('connection', test.connect.bind(test)); `
// this updates the associate id and url from ws.upgradeReq. but I see uws.upgradeReq is undefined. Why is that? 
wss is as below : 
```
 websockets WebSocket {
test_1  |   events: {},
test_1  |   OPEN: 1,
test_1  |   CLOSED: 0,
test_1  |   external: [External],
test_1  |   executeOn: 'server' }
```

**Comment by goriunov** [comment]
@smoholkar  `upgradeReq` is a second parameter you can find it in README. 

```
/**
 * To accept WebSocket connections use on connection method
 * 
 * socket: WebSocket client
 * upgReq: upgrade request
*/
server.on('connection', (socket, upgReq) => {
.....

```

**Comment by smoholkar** [comment]
@goriunov I'm a bit confused. The below is the working config using uws. 
`wss.on('connection', test.connect.bind(test));`
test.connect(ws) will receive the upgrade request headers and url which it uses to register users. 

converting the above to use this library:
server.on('connection', (socket, upgReq) => { what should upgReq exactly be ?

**Comment by goriunov** [comment]
Data is the same as in `uws` so if you want to make it the same as uws just write it some thing like that:


```js
// just an example

server.on('connection', (socket, upgReq) => {
    socket.upgradeReq = upgReq;
    test.connect.call(test, socket);
});
```

**Comment by goriunov** [comment]
Proper `handleUpgrade` (`ws` like) is coming in version 1.0.0 (this release will include other things to make it more like `ws` module)

**Comment by goriunov** [comment]
@Kamil93 version 1.0.0 has been released with proper `handleUpgrade` closing this issue.
