### ISSUE TITLE
Keyword "declare" missing

### ISSUE THREAD

**Issue by Shadowpriestdazzle** [ClusterWS/cWS#14]
Hello. I am not an experienced coder, but in my project with node 10.14.2 it didn't let me compile your module without changing two lines in the index.d.ts file from `const WebSocket_base: any;` to `declare const WebSocket_base: any;`.
Apart from that it seems to work flawlessly for me.

**Comment by goriunov** [comment]
@Shadowpriestdazzle  i have released new version 0.11.1 which should fix that issue.
