### ISSUE TITLE
Can I use it with redis?

### ISSUE THREAD

**Issue by jawadakram20** [ClusterWS/cWS#17]
I was wondering if I can use it with Redis and bull and how can I handle millions of connections.

**Comment by goriunov** [comment]
`cWS` is simply websocket library you can use it with whatever you would like (including redis) however you will need to write your own code to connect in together with redis. 

About `how can I handle millions of connections` this question is not that simple to answer, there are quite a few things which needs to be done and it really depends on your application use case and approach you choose to scale it to 1m.
