### ISSUE TITLE
Sending buffers with OPCODE_TEXT

### ISSUE THREAD

**Issue by tadeuszwojcik** [ClusterWS/cWS#18]
Hi,

I was wondering if you'd accept pull request that would allow specifying OPCODE_TEXT for messages that aren't strings. I have use case where I already have buffer and the only way to send it as 'text' is to call `toString` on it which seems bit wasteful. Does it make sense?

**Comment by goriunov** [comment]
Before creating PR can you check if it is actually going to work when u pass OPCODE_TEXT and binary data. Also why don't you just decode it from binary to text on client ?

**Comment by tadeuszwojcik** [comment]
It's working fine, and actually `uWebsockets` and `ws` allow that. Unfortunately I can't really change client side of the websocket connection that expects text data.
I think in https://github.com/ClusterWS/cWS/blob/master/lib/cws/client.ts#L128 there is no need for checking for 'typeof message !== 'string'  .  If someone wants to send as binary set's the flag if not doesn't that's it (it's how it's set in uWebsockets as well https://github.com/uNetworking/uWebSockets.js/blob/master/src/WebSocketWrapper.h#L110). 

Would that make sense?

**Comment by goriunov** [comment]
I see, sounds good, i would like to keep `typeof message !== 'string'`  can you restructure code so that if you pass `options.binary` as `false`  it will force OPCODE_TEXT, in that case it wont be as breaking change. Thank you.

**Comment by tadeuszwojcik** [comment]
Done, hope it's what you had in mind.

**Comment by goriunov** [comment]
Thank you :) 0.15.0 released with this change.

**Comment by tadeuszwojcik** [comment]
Thanks!
