### ISSUE TITLE
Broken close frame

### ISSUE THREAD

**Issue by edreal** [ClusterWS/cWS#22]
In chrome sometimes I get:

> "WebSocket connection to '[ws://ADDRESS]' failed: Received a broken close frame containing a reserved status code."

I never seen this error on normal ws lib. Is it something that needs to worried about?

**Comment by goriunov** [comment]
That is an interesting, would give more description what are the conditions to reproduce. I have tried running it but could not reproduce. Would be good to include operating system, browser version, cws version, Node.js version and steps to reproduce :) Thanks.

**Comment by edreal** [comment]
Yea ofcouse :)

Cws v0.15.0 (in package.json)
Node.js v8.15.1
Chrome 76 on Windows 10

I get it everytime when I close the ws with ws.close().
In Uws v10.148.1 this doesn't happen.

**Comment by goriunov** [comment]
Thanks for information :)

cws is just a port of uws without very significant changes, most of the changes are in js code which has been rewritten in TypeScript and very minor modification of c++ code to make it work with node 11, 12.

By the way when you call `ws.close()` do u do it from client side or server. I will try to have a look more in details soon.

**Comment by goriunov** [comment]
Ok issue has been confirmed will patch it and do release of new version soon :)

**Comment by goriunov** [comment]
Ok just released 0.15.2 with fix for that issue.

**Comment by edreal** [comment]
Great! I'l close this 👍
