### ISSUE TITLE
Should I use this with something like msgpack?

### ISSUE THREAD

**Issue by seiyria** [ClusterWS/cWS#23]
I see that clusterws supports compress and binary for sending messages to clients. Should I use msgpack before I compress and/or binary send a message, and then unpack it on the client?

**Comment by goriunov** [comment]
If you have large messages it may be useful to compress, if you send many small message it adds more overhead. msgpack is good to reduce message size. You definitely can use compression and encode data with msgpack and send it as binary, but to actually see if it gives you any benefits you may want to write small bench test which will reproduce your actual application use case and then see if combining this options helps.

**Comment by seiyria** [comment]
Thanks, I just wanted to make sure it wasn't redundant to do this! I'll have to evaluate the messages I send and see what makes sense.
