### ISSUE TITLE
can i use this on web ? i got an error 

### ISSUE THREAD

**Issue by Dj-jom2x** [ClusterWS/cWS#26]
cws_.*_.*$:26 Uncaught Error: Cannot find module './cws_undefined_undefined' check './node_modules/@clusterws/cws/build_log.txt' for post install build logs

**Comment by goriunov** [comment]
@Dj-jom2x this is server and nodejs client only, browsers have default websocket client 
 [example](https://javascript.info/websocket)

**Comment by Dj-jom2x** [comment]
oh i see hahahah xD sorry i was doing like socket io hahah i thought that also the case here.

**Comment by goriunov** [comment]
Socket io is basically built on top of default browser websocket protocol :)

**Comment by Dj-jom2x** [comment]
I use this and create angular module from it https://www.npmjs.com/package/clusterws-client-js 

but im having xD trouble with emit..  i did see "Socket connected" tho good sign.. xD

**Comment by Dj-jom2x** [comment]
hmm how long does the connecting goes  

Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

I need to use OnInit for guards hehehe 

btw whats he equavalent of emit here?

i see on docs https://github.com/ClusterWS/ClusterWS-Client-JS/wiki/Handle-Socket

That I can do this

```
 //client
 this.socket.send("hello", {a:1})
//server
    socket.on("hello", (msg) => {
        console.log(msg)
    })

```
but it seems not working but it goes on 
```
   socket.on('message', async (message) => {
      console.log(11,message);
    });
```
that works but it looks like this

```
11 {"#":["e",{"0":"hello","1":{"a":1}},null]}
```

**Comment by goriunov** [comment]
@Dj-jom2x clusterws-client-js was only designed to communicate with clusterws server, unfortunately it is not good idea to use it with any other server. there is no emit logic in that library and  clusterws-client-js will be deprecated after clusterws 4 release as protocol set up moved to user repressibility. before you send messages from client to server you need to make sure it is connected with on connect handler 

```
socket.on('connect', () => {
   socket.send('event', 'message')
})
```
