### ISSUE TITLE
Unresolved Symbol in dist binary

### ISSUE THREAD

**Issue by BastienDurel** [ClusterWS/cWS#31]
Hello,

mastodon is using @clusterws/cws, and since I upgraded, it does not run anymore, because of a missing symbol in dist/cws_linux_72.node :

```Error: Error relocating /home/mastodon/live/node_modules/@clusterws/cws/dist/cws_linux_72.node: _ZN4node6AssertEPA4_KPKc: symbol not found```

This symbol can be demangled as : ```node::Assert(char const* const (*) [4])```

I'm using node v12.14.0, I purged node_modules & yarn caches, rebuilt via `yarn install`, but cannot make node start again. Here is the [initial report](https://github.com/tootsuite/mastodon/issues/12656)

**Comment by goriunov** [comment]
Hi @BastienDurel thanks for reporting this issue, i am looking that.

**Comment by goriunov** [comment]
@BastienDurel i have released new version 0.16.1 that should fix above issue.

**Comment by BastienDurel** [comment]
It works, thanks ! :)
