### ISSUE TITLE
upgraded from 0.16.0 to 1.1.2 - getting cWs invalid status code or invalid UTF-8 sequence

### ISSUE THREAD

**Issue by seiyria** [ClusterWS/cWS#34]
Was there something I should have changed with the way my data is sent or received when I upgraded? It seems like this error is thrown when I send data to the client. I send data as follows:

```
  private transformData(data) {
    return JSON.stringify(data);
  }

  // emit message directly to socket
  private sendToSocket(socket, data) {
    const sendMessage = this.transformData(data);
    socket.send(sendMessage, { binary: true, compress: true });
  }
```

**Comment by goriunov** [comment]
`{binary: true | false}` is to overwrite type which you are providing instead automatically detect. I is not going to transform your data to specified type, try removing `binary: true` and see if that will help.

**Comment by seiyria** [comment]
@goriunov thank you, that seemed to make it work!
