### ISSUE TITLE
cWs invalid status code or invalid UTF-8 sequence

### ISSUE THREAD

**Issue by edreal** [ClusterWS/cWS#39]
Calling ws.close function in browser without passing the close code causes that error.
If I call the close function with code like 3500, the error doesn't happen.
I am using cWS 1.5.0 with SSL.

**Comment by goriunov** [comment]
@edreal thank you for letting know about that issue. New version has been released 1.6.0 which should fix that issue.

**Comment by edreal** [comment]
That was quick! Thanks :D
