### ISSUE TITLE
How to get ip address inside handshake

### ISSUE THREAD

**Issue by subversivo58** [ClusterWS/cWS#40]
It's possible, get **ip** address when **"handshake"** connection is negotiate?

The use case in question would be to map connection attempts before establishing a socket connection.

All the examples I "found out there" to define a rate limit are for after the connection has been established ... what I want is to map the ip to define an abuse of attempts using (inside) the boot option `verifyClient()`

Even though there is no native method in this library, how can I get the expected result?

**Comment by goriunov** [comment]
@subversivo58 `verifyClient` gets `info` as parameter which has incoming request check that out.

https://github.com/ClusterWS/cWS/blob/96affe0b461ece10d2fda5c0dfc42828c0368ed8/dist/index.d.ts#L11

**Comment by subversivo58** [comment]
@goriunov thanks

I was just looking at the "forwarded" headers (which were not there) ... your indication made me look better at the request object

The use of `info.req.connection.remoteAddress` covered the point in question, thanks
