### ISSUE TITLE
Node 14 Support

### ISSUE THREAD

**Issue by EricRabil** [ClusterWS/cWS#41]
Hey, now that 14.0.0 has dropped, any chance Node 14 support will come for the bindings?

**Comment by goriunov** [comment]
@EricRabil i am not planning to add Node 14 right now. Will look in to that sometime later. Most likely at the same time will remove support for older versions..

**Comment by ddevault** [comment]
Maybe your downstreams shouldn't be using a bloody native library to implement bloody websockets when it won't bloody update to bloody new node versions, god dammit

**Comment by EricRabil** [comment]
@ddevault thank you for your insightful comment.

Nobody is being paid to maintain this library, and I haven't had the time to update my PR yet. If you want to pay the maintainer of this library, perhaps support will be expedited.

uWS is maintained by a paid developer who generously open-sources his work. cWS library is based off of an old version of that library before several breaking changes were introduced. **It is maintained for free and supported through optional donations.**

If you feel you can better maintain this library, go ahead and fork it. That's exactly what cWS did when uWS introduced breaking changes after 0.14. Please don't pollute communities with unhelpful comments.

**Comment by goriunov** [comment]
New version has been released

**Comment by ddevault** [comment]
Thank you.
