### ISSUE TITLE
Possible regression in cws on node 12.16.2/12.16.3

### ISSUE THREAD

**Issue by q42jaap** [ClusterWS/cWS#43]
We're using `@clusterws/cws` in a project I'm working on. I found a fatal issue when upgrading from `node v12.16.1` to `node v12.16.2`. `node v12.16.3` shows the same issue.

After lot's of digging and trying, I came up with a minimal reproducable example.

## Running
Start the server with docker-compose:
```
docker-compose -f docker-compose.yml up --build
```

Start the client (run any node version >= 8 you like):
```
node client/client.js
```

## Results
```
upgrade 101 Switching Protocols
```
It insteads fails with the error:
```
140024858339200:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:308:
```

## Issue
I suspect this is an issue with how `@clusterws/cws` handles the data, but it could very well be a bug in nodejs.

## Code
Please find the code in the repository:
https://github.com/q42jaap/cws-https-server-repro-node-12.16.2

See the successful result for 12.16.1: https://github.com/q42jaap/cws-https-server-repro-node-12.16.2/runs/650813746?check_suite_focus=true
See the failed result for 12.16.2: https://github.com/q42jaap/cws-https-server-repro-node-12.16.2/runs/650813757?check_suite_focus=true (github action sees this as cancelled, which is strange, but the result is as described above)
https://github.com/q42jaap/cws-https-server-repro-node-12.16.2/runs/650813772?check_suite_focus=true

For completeness I'll highlight the most important parts here (so it doesn't get lost):
```
// client.js
const opts = {
    headers: {
        'Sec-WebSocket-Version': 13,
        'Sec-WebSocket-Key': '313fKCkB2zmpkrYaDOV5VF==',
        Connection: 'Upgrade',
        Upgrade: 'websocket',
    },
    rejectUnauthorized: false,
    checkServerIdentity() {
        return true;
    },
    createConnection(options) {
        options.path = undefined;
        options.servername = options.host;
        return tls.connect(options);
    },
    host: 'localhost',
    path: '/',
    port: 8443,
};

const tls = require('tls');
const https = require('https');
const req = https.get(opts);
req.on('error', (error) => {
    console.error("error", error);
});
req.on('response', (res) => {
    console.log("response", res.statusCode, res.statusMessage);
});
req.on('upgrade', (res, socket, head) => {
    console.log("upgrade", res.statusCode, res.statusMessage)
});
```

```
// server.js
const cws = require("@clusterws/cws");
const fs = require("fs");
const https = require("https");

const port = 8443;
const serverOptions = {
    cert: fs.readFileSync("server.crt", "utf8"),
    key: fs.readFileSync("server.key", "utf8"),
    ciphers: "",
    secureProtocol: "TLSv1_2_method",
};
const server = https.createServer(serverOptions).listen(port, "0.0.0.0", () => {
    console.log("Started server");
});

const wss = new cws.WebSocketServer({ server });
wss.on("connection", (ws) => {
    console.log("client connected");
    ws.on("error", (...args) => console.log("connection error", args));
    ws.on("close", (...args) => console.log("connection close", args));
});
wss.on("error", (...args) => {
    console.log("server error", ...args);
});
```

**Comment by q42jaap** [comment]
I noticed travis currently builds v12.15. The issue first surfaces in v12.16.2.

node v10.20.1 has the same openssl as 12.16.2 (1.1.1e), but it not affected (openssl change was our initial hunch, but it's more complex than that).

**Comment by goriunov** [comment]
@q42jaap Thank you for your investigation, this is most likely related to the SSL version upgrade. Which requires manually bindings rebuild unfortunately after rebuild it wont properly run on node 12.15 and less. I will try to run rebuild and confirm the issue. If it is the case will create table in readme with cws version to supported node js versions !

**Comment by goriunov** [comment]
@q42jaap just released version 2.0.0 which should fix issues with latest node 12 and removes some unsupported node js versions. Also there is new table for supported node versions in README.md https://github.com/ClusterWS/cWS#supported-node-versions

**Comment by q42jaap** [comment]
@goriunov Thanks for your fast response! We'll test with cWs 2.0 soon.

**Comment by q42jaap** [comment]
It's working for us, thanks!
