### ISSUE TITLE
node10 SSL alert number 10

### ISSUE THREAD

**Issue by SirAnthony** [ClusterWS/cWS#6]
Hello,

As I can see, code taken not from uws repo, but my fork of uWebSockets-binding, to build on node10. Please note, this does not work on node 10 for some ssl ws messages after parser tweaking (worked well on node8). I'm still investigating issue (spent few weeks already), but it seems node changed http_parser/socket interaction, and uws socket interaction should be altered too.

Error hook for search engines:
```
Error: 140682218641280:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 10
```

**Comment by goriunov** [comment]
Thank you, i will also do research about that.

**Comment by SirAnthony** [comment]
https://github.com/ClusterWS/uWS/blob/master/src/Socket.h#L190
There is the line, where ssl read error coming from.

**Comment by goriunov** [comment]
That is a good news :)

**Comment by goriunov** [comment]
I have added your info to the README and link to your fork as well. Also if you would like you can contribute to this repo as i am planning to support it properly at least till version 0.15 for Node.js comes out.    Thank you.

**Comment by SirAnthony** [comment]
It seems, issue can be split into 2 parts:
- ssl alert received from client (can be any kind of server-client interaction error), we will continue of investigation of it, but it is not blocker for us.
- uws does not handle _tlsError/error events of socket, and node throws it as unhandledException.
I added [hack](https://github.com/hola/uWebSockets-bindings/blob/master/nodejs/src/uws.js#L422) in my branch, it just add handler for such exceptions, to stop it from failing to unhandled. I do not like that solution, so it is up to you, what to do with it.

**Comment by goriunov** [comment]
Thanks, i have updated to the latest changes :)

**Comment by Kamil93** [comment]
Is there anything new about this issue? Still websocket transport doesn't work with SSL

**Comment by goriunov** [comment]
@Kamil93 it should work alright, can you send an error you get. Also in case if you can not set up proper ssl in node app you can use something like `nginx` with ssl in front of non ssl node app.

**Comment by goriunov** [comment]
Moved to https://github.com/ClusterWS/cWS/issues/28
