### ISSUE TITLE
Why not using EventEmitter from native 'events' module? 

### ISSUE THREAD

**Issue by rokoroku** [ClusterWS/cWS#9]
The original `uws` module uses custom EventEmitter class that only allows single listener per event, and so does this module.

https://github.com/ClusterWS/cWS/blob/866c00c6ed12b24ab7ea8151976ecaad63eff11b/lib/emitter.ts#L3-L20

However, IMHO, It's bit nonsence that a class named `EventEmitter` does not work as [the node.js developers known](https://nodejs.org/api/events.html#events_class_eventemitter). So rather than using custom EventEmitter (like its precedence), why not using EventEmitter from the native `events` module? (or you can use another performant implementation like eventemitter2, 3, whatever.)

---

Further Idea: EventEmitter can be replaced before creating a new WebSocket instances like how other libraries replace the Promise instance:
```js
const CustomEventEmitter = require(/* 'events' or somewhere */);
require('@custerws/cws').configs.EventEmitter = CustomEventEmitter;
```

**Comment by goriunov** [comment]
I have released version `0.10.0` you can check out readme section `Replace EventEmitter` you should be able to replace on any implementation you would like to which contain `emit` and `on` functions.

**Comment by rokoroku** [comment]
Bit worried about global pollution, but seems to work :)

**Comment by goriunov** [comment]
I have been thinking about the right approach to implement it into the existing system without changing interface much and this was one of the easiest implementation. I don't thing that global is a big issue in this particular case as we wrap it in cws object which is not common and should not interfere with anything else.   

global is just a scope same as for example function, it is better to do not assign global var without understanding (may coze some bugs) for [example](http://blog.niftysnippets.org/2008/03/horror-of-implicit-globals.html) but in cws case everything is alright as we assign it in `global.cws` scope :)
